// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdlclypmlxsamwapscwg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkbGNseXBtbHhzYW13YXBzY3dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5OTgwNTksImV4cCI6MjA3MDU3NDA1OX0.JzY5PxKF6E4DSq1sIWty8XYHwI-oJyVrtQ1bIWVo1hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});